// this script runs before `npm run build`

const path = require('path')
const fs = require('fs')
const config = require('./HyperMD.config.js')

process.chdir(path.join(__dirname, ".."))

//--------------------------------------------------------------
// Update src/ai1.ts, export all components in all-in-one bundle

var ai1_imports = []
var ai1_exports = []

for (const id in config.components) {
  const export_as = config.components[id]
  if (export_as) {
    ai1_exports.push(export_as)
    ai1_imports.push(`import * as ${export_as} from "./${id}"`)
  } else {
    ai1_imports.push(`import "./${id}"`)
  }
}

var ai1_code = `// All in one HyperMD bundle!
//
// **DO NOT EDIT!** This file is generated by rollup.config.js
//

export * from "./core"

${ai1_imports.join("\n")}

${ai1_exports.length ? ("export {\n" + ai1_exports.map(x => `  ${x},\n`).join("") + "}") : ("// No more exports")}
`

fs.writeFileSync("./src/ai1.ts", ai1_code)
